config/routes.rb
Rails.application.routes.draw do

  resources :slides, only: [:index, :new, :create, :destroy]
  get 'slides/index'
  get 'slides/new'
  get 'slides/create'
  get 'slides/destroy'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  resources :users
  get 'welcome/index'

  root 'questions#index'

  resources :questions do
    resources :answers
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  belongs_to :original_author, class_name: "User"
  validates :title, presence: true,
                    length: {minimum: 5}
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :logged_in_user

  def new
    @question = Question.new
  end

  def edit
      @question = Question.find(params[:id])
      if @question.original_author != current_user
        flash[:danger] = "You are not the author!"
        redirect_to @question
      end
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    if @question.original_author == current_user
      @question.destroy
    else
      flash[:danger] = "You are not the author!"
    end
    redirect_to questions_path
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.where(parent_answer_id: nil)
  end

  def index
    @questions = Question.all
  end

  private
  def question_params
    params.require(:question).permit(:title, :text).merge(original_author: current_user)
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>

  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@question.errors.count, "error") %> prohibited
        this question from being saved:
      </h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/questions/edit.html.erb
<h1>Edit question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<div class="qn-list col-md-8 col-md-offset-2">
  <div class="new-qn">
  <%= link_to new_question_path, class: 'btn btn-default btn-block' do %>
    <i class="glyphicon glyphicon-plus"></i> New Question
  <% end %>
  </div>

    <% @questions.each do |question| %>
    <div class="qn-item">
      <div class="qn-title"><%= link_to question.title, question_path(question) %></div>
      <div class="qn-body"><%= question.text %></div>
      <div class="qn-links">
        <div class= "btn-group">
        <%= link_to question_path(question), title: 'reply', class: 'btn btn-default btn-sm' do %>
          <i class="glyphicon glyphicon-share-alt"></i>
        <% end %>
        <%= link_to edit_question_path(question), title: 'edit', class: 'btn btn-default btn-sm'  do %>
          <i class="glyphicon glyphicon-edit"></i>
        <% end %>
        <%= link_to question_path(question), title: 'delete', method: :delete, data: { confirm: 'Are you sure?' },
        class: 'btn btn-default btn-sm' do %>
          <i class="glyphicon glyphicon-remove"></i>
        <% end %>
        </div>
      </div>
    </div>
    <% end %>
</div>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="question">
    <div class="qn-title"><%= @question.title %></div>
    <div class="qn-text"><%= @question.text %></div>
  </div>

  <h3>Answer:</h3>
  <%= render 'answers/form' %>

  <div class="answers">
    <%= render @answers %>



    <%= link_to 'Back', questions_path %>
  </div>
</div>