config/routes.rb
Rails.application.routes.draw do

  resources :slides, only: [:index, :new, :create, :destroy]
  get 'slides/index'
  get 'slides/new'
  get 'slides/create'
  get 'slides/destroy'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  resources :users
  get 'welcome/index'

  root 'questions#index'

  resources :questions do
    resources :answers
  end

end

app/models/slide.rb
class Slide < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  # validates :name, presence: true # Make sure the owner's name is present.
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  before_action :logged_in_user, only: [:destroy]
  def index
     @slides = Slide.all
   end

   def new
     @slide = Slide.new
   end

   def create
     @slide = Slide.new(slide_params)

     if @slide.save
       redirect_to slides_path, notice: "The slide #{@slide.name} has been uploaded."
     else
       render "new"
     end
   end

   def destroy
     @slide = Slide.find(params[:id])
     @slide.destroy
     redirect_to slides_path, notice:  "The slide #{@slide.name} has been deleted."
   end

 private
   def slide_params
     params.require(:slide).permit(:name, :attachment)
   end
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/slides/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />
<%= link_to "New Slide", new_slide_path, class: "btn btn-primary" %>
<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Download Link</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @slides.each do |slide| %>
      <tr>
        <td><%= slide.name %></td>
        <td><%= link_to "Download Slide", slide.attachment_url %></td>
        <td><%= button_to "Delete",  slide, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{slide.name}?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/slides/new.html.erb
<h1>Slides#new</h1>


<% if !@slide.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @slide.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="well">
  <%= form_for @slide, html: { multipart: true } do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>