config/routes.rb
Rails.application.routes.draw do

  resources :slides, only: [:index, :new, :create, :destroy]
  get 'slides/index'
  get 'slides/new'
  get 'slides/create'
  get 'slides/destroy'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  resources :users
  get 'welcome/index'

  root 'questions#index'

  resources :questions do
    resources :answers
  end

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <!-- for mobile / small window display -->
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="glyphicon glyphicon-menu-hamburger"></span>
      </button>

      <%= link_to 'OpenFloor', root_path, :class => 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <li><%= link_to 'Questions', questions_path %></li>
        <li><%= link_to 'Slides', slides_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <ul class="nav navbar-nav">
          <li> <% if logged_in? %>
            <%= link_to 'Logout', logout_path, :method => 'delete' %>
          <% end %> </li>
          </ul>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>